name: intactness
services:
    intactness:
        # Apple Silicon
        platform: linux/amd64
        # Windows
        #platform: darwin/amd64
        #Linux AMD
        #platform: linux/amd64
        #Linux ARM
        #platform: linux/arm64
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        ports:
            - 8180:8181
        container_name: intactness
        volumes:
            - '.:/app'
        image: intactness